apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcf
  labels:
    app: mcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcf
  template:
    metadata:
      labels:
        app: mcf
    spec:
      containers:
        - image: phanikumarps/mcf:latest #change it to your image
          imagePullPolicy: Always
          name: mcf
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mcf
  labels:
    app: mcf
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: mcf
