apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcfmeta
  labels:
    app: mcfmeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcfmeta
  template:
    metadata:
      labels:
        app: mcfmeta
    spec:
      containers:
        - image: phanikumarps/mcfmeta:latest #change it to your image
          imagePullPolicy: Always
          name: mcfmeta
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mcfmeta
  labels:
    app: mcfmeta
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: mcfmeta
